// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(CrudContext))]
    [Migration("20220317184531_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.15");

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("DateTime")
                        .HasColumnName("Created_at");

                    b.Property<string>("Email")
                        .HasColumnType("char(200)")
                        .HasColumnName("Email");

                    b.Property<string>("Name")
                        .HasColumnType("char(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .HasColumnType("char(200)")
                        .HasColumnName("Password");

                    b.Property<DateTime>("Updated_at")
                        .HasColumnType("DateTime")
                        .HasColumnName("Updated_at");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
